[
  {
    "id" : "bf39f9fb-3372-4863-be8e-778929d91005",
    "prId" : 1296,
    "comments" : [
      {
        "id" : "bccf42b9-5c55-49ab-8a90-2f68e69ae432",
        "parentId" : null,
        "author" : {
          "login" : "hurryabit",
          "name" : "Martin Huschenbett",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/11665611?u=7dbd00d5e7ea53919ed31dc4200f602ebca91c8f&v=4"
        },
        "body" : "@remyhaemmerle-da This test fails because an `EUnknownDefinition` exception is thrown. If I replace `PositiveTestCase1:SerializableRecord` with just `SerializableRecord` then the test passed. If I replace it with `SerializableRecordXYZ`, it still passes even though it should fail with `EUnknownDefinition` definition. This doesn't make any sense. Could you please have a look.",
        "createdAt" : "2019-05-21T19:21:02Z",
        "updatedAt" : "2019-05-22T09:39:29Z",
        "lastEditedBy" : {
          "login" : "hurryabit",
          "name" : "Martin Huschenbett",
          "avatarUrl" : "https://avatars0.githubusercontent.com/u/11665611?u=7dbd00d5e7ea53919ed31dc4200f602ebca91c8f&v=4"
        },
        "tags" : [
        ]
      }
    ],
    "commit" : "3537333f3e4096578991918b103ac47fcc6cdf6c",
    "line" : 81,
    "diffHunk" : "@@ -1,1 +251,255 @@            record @serializable SerializableRecord = {};\n\n            record @serializable UnserializableContractId = { cid : ContractId PositiveTestCase1:SerializableRecord };\n          }\n"
  }
]